image: python:3.8

include:
  - template: Code-Quality.gitlab-ci.yml

services:
    - docker:dind

stages:
    - test
    - deploy

deploy:
    stage: deploy
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    before_script:
        - pip install twine
        - python setup.py sdist
    script:
        - twine upload dist/*
    only:
        - tags